### ISSUE TITLE
Default interactions for plants

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/seinet#1]
@jhpoelen on herbarium labels (like coming from Seinet) collectors will list other plant species in the same area in the AssociatedTaxa field. I think it is worth considering using http://purl.obolibrary.org/obo/RO_0008506,  ecologically co-occurs with, as default from herbarium specimens.

**Comment by jhpoelen** [comment]
Good point! Would you mind adding the default "blank" interaction type mapping for this RSS feed? If not, I'd be happy to add.

**Comment by seltmann** [comment]
@jhpoelen added interaction_types_mapping.csv to the repository with blank to http://purl.obolibrary.org/obo/RO_0008506
